config/routes.rb
Rails.application.routes.draw do
  resources :fotos

end

app/models/foto.rb
class Foto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :set_foto, only: [:show, :edit, :update, :destroy]

  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.all
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
  end

  # GET /fotos/new
  def new
    @foto = Foto.new
  end

  # GET /fotos/1/edit
  def edit
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = Foto.new(foto_params)

    respond_to do |format|
      if @foto.save
        format.html { redirect_to @foto, notice: 'Foto was successfully created.' }
        format.json { render :show, status: :created, location: @foto }
      else
        format.html { render :new }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fotos/1
  # PATCH/PUT /fotos/1.json
  def update
    respond_to do |format|
      if @foto.update(foto_params)
        format.html { redirect_to @foto, notice: 'Foto was successfully updated.' }
        format.json { render :show, status: :ok, location: @foto }
      else
        format.html { render :edit }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto.destroy
    respond_to do |format|
      format.html { redirect_to fotos_url, notice: 'Foto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foto
      @foto = Foto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foto_params
      params.require(:foto).permit(:name, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/_form.html.erb
<%= form_for(@foto) do |f| %>
  <% if @foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

      <ul>
      <% @foto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fotos/edit.html.erb
<h1>Editing Foto</h1>

<%= render 'form' %>

<%= link_to 'Show', @foto %> |
<%= link_to 'Back', fotos_path %>

app/views/fotos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fotos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fotos.each do |foto| %>
      <tr>
        <td><%= foto.name %></td>
        <td><%= foto.image_url %></td>
        <td><%= link_to 'Show', foto %></td>
        <td><%= link_to 'Edit', edit_foto_path(foto) %></td>
        <td><%= link_to 'Destroy', foto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foto', new_foto_path %>

app/views/fotos/new.html.erb
<h1>New Foto</h1>

<%= render 'form' %>

<%= link_to 'Back', fotos_path %>

app/views/fotos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @foto.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @foto.image_url %>
</p>

<%= link_to 'Edit', edit_foto_path(@foto) %> |
<%= link_to 'Back', fotos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsJqueryFileUploadS3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>